name: Pytest
on: [push, pull_request, workflow_dispatch]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Run tests
        run: pytest --cov
      - name: Tests report
        run: coverage report
      - name: Run linter
        run: flake8
