name: Pytest
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install requirements
        run: pip install -r requirements.txt
        
      - name: Run tests
        run: pytest
      
      - name: Call coverage report
        run: coverage report
        
      - name: Run linter
        run: flake8

